version: '3'
services:
  bitrix:
    build:
      dockerfile: dockerfile
    hostname: bitrix
    #container_name: bitrix
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    

    